
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(497, 490)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.algorithm = QtGui.QComboBox(self.centralwidget)
        self.algorithm.setObjectName(_fromUtf8("algorithm"))
        self.algorithm.addItem(_fromUtf8(""))
        self.algorithm.addItem(_fromUtf8(""))
        self.algorithm.addItem(_fromUtf8(""))
        self.algorithm.addItem(_fromUtf8(""))
        self.algorithm.addItem(_fromUtf8(""))
        #Next line added in Vasilenko version, but I dont understand why, so I comment it
        #self.algorithm.setCurrentIndex(4)
        self.verticalLayout.addWidget(self.algorithm)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.execNum = QtGui.QSpinBox(self.centralwidget)
        self.execNum.setMinimum(1)
        self.execNum.setMaximum(1000)
        self.execNum.setObjectName(_fromUtf8("execNum"))
        self.verticalLayout.addWidget(self.execNum)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.line_8 = QtGui.QFrame(self.centralwidget)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.verticalLayout_4.addWidget(self.line_8)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_4.addWidget(self.label_6)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.sysconfname = QtGui.QLineEdit(self.centralwidget)
        self.sysconfname.setObjectName(_fromUtf8("sysconfname"))
        self.horizontalLayout.addWidget(self.sysconfname)
        self.toolButton_2 = QtGui.QToolButton(self.centralwidget)
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))
        self.horizontalLayout.addWidget(self.toolButton_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_10.addWidget(self.pushButton_2)
        self.pushButton_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_10.addWidget(self.pushButton_3)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.line_10 = QtGui.QFrame(self.centralwidget)
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.verticalLayout_4.addWidget(self.line_10)
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_4.addWidget(self.label_15)
        self.result_filename = QtGui.QLineEdit(self.centralwidget)
        self.result_filename.setObjectName(_fromUtf8("result_filename"))
        self.verticalLayout_4.addWidget(self.result_filename)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.line_7 = QtGui.QFrame(self.centralwidget)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.verticalLayout_4.addWidget(self.line_7)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_10.addWidget(self.label_5)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.MI = QtGui.QCheckBox(self.centralwidget)
        self.MI.setObjectName(_fromUtf8("MI"))
        self.horizontalLayout_16.addWidget(self.MI)
        self.maxIter = QtGui.QSpinBox(self.centralwidget)
        self.maxIter.setMinimum(1)
        self.maxIter.setMaximum(1000000)
        self.maxIter.setProperty("value", 30)
        self.maxIter.setObjectName(_fromUtf8("maxIter"))
        self.horizontalLayout_16.addWidget(self.maxIter)
        self.verticalLayout_10.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.MIWCH = QtGui.QCheckBox(self.centralwidget)
        self.MIWCH.setObjectName(_fromUtf8("MIWCH"))
        self.horizontalLayout_17.addWidget(self.MIWCH)
        self.maxIterWCH = QtGui.QSpinBox(self.centralwidget)
        self.maxIterWCH.setMinimum(1)
        self.maxIterWCH.setMaximum(500000)
        self.maxIterWCH.setProperty("value", 15)
        self.maxIterWCH.setObjectName(_fromUtf8("maxIterWCH"))
        self.horizontalLayout_17.addWidget(self.maxIterWCH)
        self.verticalLayout_10.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.MR = QtGui.QCheckBox(self.centralwidget)
        self.MR.setObjectName(_fromUtf8("MR"))
        self.horizontalLayout_18.addWidget(self.MR)
        self.MinRel = QtGui.QDoubleSpinBox(self.centralwidget)
        self.MinRel.setDecimals(4)
        self.MinRel.setMaximum(1.0)
        self.MinRel.setSingleStep(0.0001)
        self.MinRel.setProperty("value", 0.5)
        self.MinRel.setObjectName(_fromUtf8("MinRel"))
        self.horizontalLayout_18.addWidget(self.MinRel)
        self.verticalLayout_10.addLayout(self.horizontalLayout_18)
        self.verticalLayout_3.addLayout(self.verticalLayout_10)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_11.addLayout(self.verticalLayout_4)
        self.line_5 = QtGui.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.horizontalLayout_11.addWidget(self.line_5)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem5)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_5.addWidget(self.label_7)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_8.addWidget(self.label_9)
        self.mincost = QtGui.QLabel(self.centralwidget)
        self.mincost.setObjectName(_fromUtf8("mincost"))
        self.horizontalLayout_8.addWidget(self.mincost)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_9.addWidget(self.label_8)
        self.maxcost = QtGui.QLabel(self.centralwidget)
        self.maxcost.setObjectName(_fromUtf8("maxcost"))
        self.horizontalLayout_9.addWidget(self.maxcost)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_7.addWidget(self.label_10)
        self.limitcost = QtGui.QLineEdit(self.centralwidget)
        self.limitcost.setObjectName(_fromUtf8("limitcost"))
        self.horizontalLayout_7.addWidget(self.limitcost)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.verticalLayout_5.addLayout(self.verticalLayout_8)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_2.addWidget(self.label_4)
        self.checktime_yes = QtGui.QRadioButton(self.centralwidget)
        self.checktime_yes.setEnabled(True)
        self.checktime_yes.setCheckable(True)
        self.checktime_yes.setChecked(False)
        self.checktime_yes.setObjectName(_fromUtf8("checktime_yes"))
        self.verticalLayout_2.addWidget(self.checktime_yes)
        self.checktime_no = QtGui.QRadioButton(self.centralwidget)
        self.checktime_no.setChecked(True)
        self.checktime_no.setObjectName(_fromUtf8("checktime_no"))
        self.verticalLayout_2.addWidget(self.checktime_no)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_5.addWidget(self.label_12)
        self.mintime = QtGui.QLabel(self.centralwidget)
        self.mintime.setObjectName(_fromUtf8("mintime"))
        self.horizontalLayout_5.addWidget(self.mintime)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.verticalLayout_9.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_12.addWidget(self.label_11)
        self.maxtime = QtGui.QLabel(self.centralwidget)
        self.maxtime.setObjectName(_fromUtf8("maxtime"))
        self.horizontalLayout_12.addWidget(self.maxtime)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem9)
        self.verticalLayout_9.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_6.addWidget(self.label_13)
        self.limittimes = QtGui.QLineEdit(self.centralwidget)
        self.limittimes.setObjectName(_fromUtf8("limittimes"))
        self.horizontalLayout_6.addWidget(self.limittimes)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        self.verticalLayout_5.addLayout(self.verticalLayout_9)
        self.verticalLayout_7.addLayout(self.verticalLayout_5)
        self.line_6 = QtGui.QFrame(self.centralwidget)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.verticalLayout_7.addWidget(self.line_6)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem10)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_11.addWidget(self.label_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.penalty = QtGui.QComboBox(self.centralwidget)
        self.penalty.setObjectName(_fromUtf8("penalty"))
        self.penalty.addItem(_fromUtf8(""))
        self.penalty.addItem(_fromUtf8(""))
        self.penalty.addItem(_fromUtf8(""))
        self.penalty.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.penalty)
        self.number = QtGui.QLineEdit(self.centralwidget)
        self.number.setEnabled(False)
        self.number.setMouseTracking(False)
        self.number.setObjectName(_fromUtf8("number"))
        self.horizontalLayout_2.addWidget(self.number)
        self.verticalLayout_11.addLayout(self.horizontalLayout_2)
        self.verticalLayout_7.addLayout(self.verticalLayout_11)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem11)
        self.horizontalLayout_11.addLayout(self.verticalLayout_7)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.line_9 = QtGui.QFrame(self.centralwidget)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.verticalLayout_6.addWidget(self.line_9)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem12)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.pushButton_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem13)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_6, 1, 1, 1, 1)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 2, 1, 1, 1)
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout.addWidget(self.line_3, 1, 2, 1, 1)
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout.addWidget(self.line_4, 0, 1, 1, 1)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 497, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_as = QtGui.QAction(MainWindow)
        self.actionSave_as.setObjectName(_fromUtf8("actionSave_as"))
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionEdit = QtGui.QAction(MainWindow)
        self.actionEdit.setObjectName(_fromUtf8("actionEdit"))
        self.actionSave_2 = QtGui.QAction(MainWindow)
        self.actionSave_2.setObjectName(_fromUtf8("actionSave_2"))
        self.actionSave_as_2 = QtGui.QAction(MainWindow)
        self.actionSave_as_2.setObjectName(_fromUtf8("actionSave_as_2"))
        self.actionOpen_2 = QtGui.QAction(MainWindow)
        self.actionOpen_2.setObjectName(_fromUtf8("actionOpen_2"))
        self.actionEdit_2 = QtGui.QAction(MainWindow)
        self.actionEdit_2.setObjectName(_fromUtf8("actionEdit_2"))

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.SetAlgParameters)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.Random)
        QtCore.QObject.connect(self.pushButton_3, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.SaveSysConf)
        QtCore.QObject.connect(self.limitcost, QtCore.SIGNAL(_fromUtf8("editingFinished()")), MainWindow.InputCostLimit)
        QtCore.QObject.connect(self.limittimes, QtCore.SIGNAL(_fromUtf8("editingFinished()")), MainWindow.InputTimeLimits)
        QtCore.QObject.connect(self.checktime_no, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.no_checked)
        QtCore.QObject.connect(self.checktime_yes, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.yes_checked)
        QtCore.QObject.connect(self.toolButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.OpenSysConf)
        QtCore.QObject.connect(self.sysconfname, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), MainWindow.LoadSysConf)
        QtCore.QObject.connect(self.penalty, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.changedPenalty)
        QtCore.QObject.connect(self.number, QtCore.SIGNAL(_fromUtf8("textEdited(QString)")), MainWindow.editPen)
        QtCore.QObject.connect(self.algorithm, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), MainWindow.AlgChanged)
        QtCore.QObject.connect(self.MI, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.use_StopConditionMaxIter)
        QtCore.QObject.connect(self.MIWCH, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.use_StopConditionMaxIterWCH)
        QtCore.QObject.connect(self.MR, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.use_StopConditionMinRel)
        QtCore.QObject.connect(self.pushButton_4, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.showLinks)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Select Algorithm:", None))
        self.algorithm.setItemText(0, _translate("MainWindow", "Genetic Algorithm", None))
        self.algorithm.setItemText(1, _translate("MainWindow", "Hybrid Genetic Algorithm", None))
        self.algorithm.setItemText(2, _translate("MainWindow", "Greedy Algorithm", None))
        self.algorithm.setItemText(3, _translate("MainWindow", "Simulated Annealing", None))
        self.algorithm.setItemText(4, _translate("MainWindow", "Hybrid of all!", None))
        self.algorithm.setItemText(5, _translate("MainWindow", "Tabu Search Algorithm", None))
        self.algorithm.setItemText(6, _translate("MainWindow", "Tabu Search Simulated Annealing", None))
        self.algorithm.setItemText(7, _translate("MainWindow", "Tabu Search Random Algorithm", None))
        self.algorithm.setItemText(8, _translate("MainWindow", "Random Algorithm", None))
        self.algorithm.setItemText(9, _translate("MainWindow", "Self-learning Genetic Algorithm", None))
        self.label_2.setText(_translate("MainWindow", "Number of executions:", None))
        self.label_6.setText(_translate("MainWindow", "System config file:", None))
        self.toolButton_2.setText(_translate("MainWindow", "...", None))
        self.pushButton_2.setText(_translate("MainWindow", "Random", None))
        self.pushButton_3.setText(_translate("MainWindow", "Save as ...", None))
        self.label_15.setText(_translate("MainWindow", "Result filename:", None))
        self.label_5.setText(_translate("MainWindow", "Stop Conditions:", None))
        self.MI.setText(_translate("MainWindow", "Maximal Number Of Iterations:", None))
        self.MIWCH.setText(_translate("MainWindow", "Maximal Number Of Iterations Without :", None))
        self.MR.setText(_translate("MainWindow", "Minimal Reliability:", None))
        self.label_7.setText(_translate("MainWindow", "System Configuration:", None))
        self.label_9.setText(_translate("MainWindow", "Min Cost:", None))
        self.mincost.setText(_translate("MainWindow", "--", None))
        self.label_8.setText(_translate("MainWindow", "Max Cost:", None))
        self.maxcost.setText(_translate("MainWindow", "--", None))
        self.label_10.setText(_translate("MainWindow", "Cost Limit:", None))
        self.label_4.setText(_translate("MainWindow", "Check Time:", None))
        self.checktime_yes.setText(_translate("MainWindow", "Yes", None))
        self.checktime_no.setText(_translate("MainWindow", "No", None))
        self.label_12.setText(_translate("MainWindow", "Min Times:", None))
        self.mintime.setText(_translate("MainWindow", "--", None))
        self.label_11.setText(_translate("MainWindow", "Max Times:", None))
        self.maxtime.setText(_translate("MainWindow", "--", None))
        self.label_13.setText(_translate("MainWindow", "Times Limits:", None))
        self.label_3.setText(_translate("MainWindow", "Penalty Function:", None))
        self.penalty.setItemText(0, _translate("MainWindow", "Exponent", None))
        self.penalty.setItemText(1, _translate("MainWindow", "Logarithm", None))
        self.penalty.setItemText(2, _translate("MainWindow", "Power", None))
        self.penalty.setItemText(3, _translate("MainWindow", "None", None))
        self.pushButton.setText(_translate("MainWindow", "Set Algorithm Parameters", None))
        self.pushButton_4.setText(_translate("MainWindow", "Show System Links", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionSave_as.setText(_translate("MainWindow", "Save as ...", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.actionEdit.setText(_translate("MainWindow", "Edit", None))
        self.actionSave_2.setText(_translate("MainWindow", "Save", None))
        self.actionSave_as_2.setText(_translate("MainWindow", "Save as ...", None))
        self.actionOpen_2.setText(_translate("MainWindow", "Open", None))
        self.actionEdit_2.setText(_translate("MainWindow", "Edit", None))

import resources_rc
