
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SLGADialog(object):
    def setupUi(self, SLGADialog):
        SLGADialog.setObjectName(_fromUtf8("SLGADialog"))
        SLGADialog.resize(443, 515)
        self.gridLayout = QtGui.QGridLayout(SLGADialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_3 = QtGui.QLabel(SLGADialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_8.addWidget(self.label_3)
        self.yes = QtGui.QRadioButton(SLGADialog)
        self.yes.setObjectName(_fromUtf8("yes"))
        self.horizontalLayout_8.addWidget(self.yes)
        self.no = QtGui.QRadioButton(SLGADialog)
        self.no.setChecked(True)
        self.no.setObjectName(_fromUtf8("no"))
        self.horizontalLayout_8.addWidget(self.no)
        self.verticalLayout_11.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(SLGADialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.algconfname = QtGui.QLineEdit(SLGADialog)
        self.algconfname.setObjectName(_fromUtf8("algconfname"))
        self.horizontalLayout_2.addWidget(self.algconfname)
        self.toolButton = QtGui.QToolButton(SLGADialog)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.horizontalLayout_2.addWidget(self.toolButton)
        self.verticalLayout_11.addLayout(self.horizontalLayout_2)
        self.label_10 = QtGui.QLabel(SLGADialog)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_11.addWidget(self.label_10)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_2 = QtGui.QLabel(SLGADialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_5.addWidget(self.label_2)
        self.popNum = QtGui.QSpinBox(SLGADialog)
        self.popNum.setMinimum(1)
        self.popNum.setMaximum(100)
        self.popNum.setProperty("value", 30)
        self.popNum.setObjectName(_fromUtf8("popNum"))
        self.horizontalLayout_5.addWidget(self.popNum)
        self.verticalLayout_11.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_6 = QtGui.QLabel(SLGADialog)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_8.addWidget(self.label_6)
        self.cp = QtGui.QHBoxLayout()
        self.cp.setObjectName(_fromUtf8("cp"))
        self.cp1 = QtGui.QDoubleSpinBox(SLGADialog)
        self.cp1.setDecimals(2)
        self.cp1.setMaximum(1.0)
        self.cp1.setSingleStep(0.01)
        self.cp1.setProperty("value", 0.6)
        self.cp1.setObjectName(_fromUtf8("cp1"))
        self.cp.addWidget(self.cp1)
        self.cp2 = QtGui.QDoubleSpinBox(SLGADialog)
        self.cp2.setMaximum(1.0)
        self.cp2.setSingleStep(0.01)
        self.cp2.setProperty("value", 0.7)
        self.cp2.setObjectName(_fromUtf8("cp2"))
        self.cp.addWidget(self.cp2)
        self.cp3 = QtGui.QDoubleSpinBox(SLGADialog)
        self.cp3.setMaximum(1.0)
        self.cp3.setSingleStep(0.01)
        self.cp3.setProperty("value", 0.8)
        self.cp3.setObjectName(_fromUtf8("cp3"))
        self.cp.addWidget(self.cp3)
        self.verticalLayout_8.addLayout(self.cp)
        self.label_7 = QtGui.QLabel(SLGADialog)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_8.addWidget(self.label_7)
        self.pc = QtGui.QHBoxLayout()
        self.pc.setObjectName(_fromUtf8("pc"))
        self.pc1 = QtGui.QDoubleSpinBox(SLGADialog)
        self.pc1.setMaximum(1.0)
        self.pc1.setSingleStep(0.01)
        self.pc1.setProperty("value", 0.4)
        self.pc1.setObjectName(_fromUtf8("pc1"))
        self.pc.addWidget(self.pc1)
        self.pc2 = QtGui.QDoubleSpinBox(SLGADialog)
        self.pc2.setMaximum(1.0)
        self.pc2.setSingleStep(0.01)
        self.pc2.setProperty("value", 0.6)
        self.pc2.setObjectName(_fromUtf8("pc2"))
        self.pc.addWidget(self.pc2)
        self.pc3 = QtGui.QDoubleSpinBox(SLGADialog)
        self.pc3.setMaximum(1.0)
        self.pc3.setSingleStep(0.01)
        self.pc3.setProperty("value", 0.8)
        self.pc3.setObjectName(_fromUtf8("pc3"))
        self.pc.addWidget(self.pc3)
        self.verticalLayout_8.addLayout(self.pc)
        self.horizontalLayout_7.addLayout(self.verticalLayout_8)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_8 = QtGui.QLabel(SLGADialog)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_4.addWidget(self.label_8)
        self.mp = QtGui.QHBoxLayout()
        self.mp.setObjectName(_fromUtf8("mp"))
        self.mp1 = QtGui.QDoubleSpinBox(SLGADialog)
        self.mp1.setMaximum(1.0)
        self.mp1.setSingleStep(0.01)
        self.mp1.setProperty("value", 0.6)
        self.mp1.setObjectName(_fromUtf8("mp1"))
        self.mp.addWidget(self.mp1)
        self.mp2 = QtGui.QDoubleSpinBox(SLGADialog)
        self.mp2.setMaximum(1.0)
        self.mp2.setSingleStep(0.01)
        self.mp2.setProperty("value", 0.7)
        self.mp2.setObjectName(_fromUtf8("mp2"))
        self.mp.addWidget(self.mp2)
        self.mp3 = QtGui.QDoubleSpinBox(SLGADialog)
        self.mp3.setMaximum(1.0)
        self.mp3.setSingleStep(0.01)
        self.mp3.setProperty("value", 0.8)
        self.mp3.setObjectName(_fromUtf8("mp3"))
        self.mp.addWidget(self.mp3)
        self.verticalLayout_4.addLayout(self.mp)
        self.label_9 = QtGui.QLabel(SLGADialog)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_4.addWidget(self.label_9)
        self.pm = QtGui.QHBoxLayout()
        self.pm.setObjectName(_fromUtf8("pm"))
        self.pm1 = QtGui.QDoubleSpinBox(SLGADialog)
        self.pm1.setMaximum(1.0)
        self.pm1.setSingleStep(0.01)
        self.pm1.setProperty("value", 0.4)
        self.pm1.setObjectName(_fromUtf8("pm1"))
        self.pm.addWidget(self.pm1)
        self.pm2 = QtGui.QDoubleSpinBox(SLGADialog)
        self.pm2.setMaximum(1.0)
        self.pm2.setSingleStep(0.01)
        self.pm2.setProperty("value", 0.6)
        self.pm2.setObjectName(_fromUtf8("pm2"))
        self.pm.addWidget(self.pm2)
        self.pm3 = QtGui.QDoubleSpinBox(SLGADialog)
        self.pm3.setMaximum(1.0)
        self.pm3.setSingleStep(0.01)
        self.pm3.setProperty("value", 0.8)
        self.pm3.setObjectName(_fromUtf8("pm3"))
        self.pm.addWidget(self.pm3)
        self.verticalLayout_4.addLayout(self.pm)
        self.horizontalLayout_7.addLayout(self.verticalLayout_4)
        self.verticalLayout_11.addLayout(self.horizontalLayout_7)
        self.label_11 = QtGui.QLabel(SLGADialog)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_11.addWidget(self.label_11)
        self.corrMode = QtGui.QComboBox(SLGADialog)
        self.corrMode.setObjectName(_fromUtf8("corrMode"))
        self.corrMode.addItem(_fromUtf8(""))
        self.corrMode.addItem(_fromUtf8(""))
        self.corrMode.addItem(_fromUtf8(""))
        self.corrMode.addItem(_fromUtf8(""))
        self.corrMode.addItem(_fromUtf8(""))
        self.corrMode.addItem(_fromUtf8(""))
        self.corrMode.addItem(_fromUtf8(""))
        self.corrMode.addItem(_fromUtf8(""))
        self.corrMode.addItem(_fromUtf8(""))
        self.corrMode.addItem(_fromUtf8(""))
        self.corrMode.addItem(_fromUtf8(""))
        self.corrMode.addItem(_fromUtf8(""))
        self.verticalLayout_11.addWidget(self.corrMode)
        self.label_12 = QtGui.QLabel(SLGADialog)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_11.addWidget(self.label_12)
        self.corrPar1 = QtGui.QDoubleSpinBox(SLGADialog)
        self.corrPar1.setDecimals(5)
        self.corrPar1.setMinimum(0.001)
        self.corrPar1.setMaximum(0.8)
        self.corrPar1.setSingleStep(0.1)
        self.corrPar1.setProperty("value", 0.1)
        self.corrPar1.setObjectName(_fromUtf8("corrPar1"))
        self.verticalLayout_11.addWidget(self.corrPar1)
        self.label_13 = QtGui.QLabel(SLGADialog)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_11.addWidget(self.label_13)
        self.corrPar2 = QtGui.QDoubleSpinBox(SLGADialog)
        self.corrPar2.setEnabled(False)
        self.corrPar2.setDecimals(5)
        self.corrPar2.setMinimum(0.001)
        self.corrPar2.setProperty("value", 0.1)
        self.corrPar2.setObjectName(_fromUtf8("corrPar2"))
        self.verticalLayout_11.addWidget(self.corrPar2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.use_metamodels = QtGui.QCheckBox(SLGADialog)
        self.use_metamodels.setObjectName(_fromUtf8("use_metamodels"))
        self.horizontalLayout_3.addWidget(self.use_metamodels, QtCore.Qt.AlignHCenter)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_5 = QtGui.QLabel(SLGADialog)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_6.addWidget(self.label_5)
        self.comboBox = QtGui.QComboBox(SLGADialog)
        self.comboBox.setEnabled(False)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.verticalLayout_6.addWidget(self.comboBox)
        self.label_4 = QtGui.QLabel(SLGADialog)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_6.addWidget(self.label_4)
        self.popControl = QtGui.QSpinBox(SLGADialog)
        self.popControl.setEnabled(False)
        self.popControl.setMinimum(3)
        self.popControl.setMaximum(100)
        self.popControl.setObjectName(_fromUtf8("popControl"))
        self.verticalLayout_6.addWidget(self.popControl)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_11.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.pushButton = QtGui.QPushButton(SLGADialog)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.metamodels_button = QtGui.QPushButton(SLGADialog)
        self.metamodels_button.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/pics/pics/chart_line.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.metamodels_button.setIcon(icon)
        self.metamodels_button.setObjectName(_fromUtf8("metamodels_button"))
        self.horizontalLayout_4.addWidget(self.metamodels_button)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_11.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout_11)
        self.verticalLayout_12.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout_12, 0, 0, 1, 1)

        self.retranslateUi(SLGADialog)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), SLGADialog.run)
        QtCore.QObject.connect(self.metamodels_button, QtCore.SIGNAL(_fromUtf8("clicked()")), SLGADialog.draw_metamodels)
        QtCore.QObject.connect(self.use_metamodels, QtCore.SIGNAL(_fromUtf8("clicked()")), SLGADialog.use_metamodels)
        QtCore.QObject.connect(self.algconfname, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), SLGADialog.loadAlgConf)
        QtCore.QObject.connect(self.toolButton, QtCore.SIGNAL(_fromUtf8("clicked()")), SLGADialog.openDialog)
        QtCore.QObject.connect(self.metamodels_button, QtCore.SIGNAL(_fromUtf8("clicked()")), SLGADialog.showMetamodelsRes)
        QtCore.QObject.connect(self.yes, QtCore.SIGNAL(_fromUtf8("clicked()")), SLGADialog.pressYes)
        QtCore.QObject.connect(self.no, QtCore.SIGNAL(_fromUtf8("clicked()")), SLGADialog.pressNo)
        QtCore.QObject.connect(self.corrMode, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), SLGADialog.corrModeChange)
        QtCore.QMetaObject.connectSlotsByName(SLGADialog)

    def retranslateUi(self, SLGADialog):
        SLGADialog.setWindowTitle(_translate("SLGADialog", "Self-learning Genetic Algorithm", None))
        self.label_3.setText(_translate("SLGADialog", "Do you want to get algorithm settings from file?", None))
        self.yes.setText(_translate("SLGADialog", "Yes", None))
        self.no.setText(_translate("SLGADialog", "No", None))
        self.label.setText(_translate("SLGADialog", "File with algorithm settings:", None))
        self.toolButton.setText(_translate("SLGADialog", "...", None))
        self.label_10.setText(_translate("SLGADialog", "Algorithm settings(not from file):", None))
        self.label_2.setText(_translate("SLGADialog", "Number of populations:", None))
        self.label_6.setText(_translate("SLGADialog", "crossPercent:", None))
        self.label_7.setText(_translate("SLGADialog", "Pcross:", None))
        self.label_8.setText(_translate("SLGADialog", "Mutation Percent:", None))
        self.label_9.setText(_translate("SLGADialog", "Pmut:", None))
        self.label_11.setText(_translate("SLGADialog", "Correction mode:", None))
        self.corrMode.setItemText(0, _translate("SLGADialog", "absolute", None))
        self.corrMode.setItemText(1, _translate("SLGADialog", "relative (subtraction)", None))
        self.corrMode.setItemText(2, _translate("SLGADialog", "relative with forgetting (subtraction)", None))
        self.corrMode.setItemText(3, _translate("SLGADialog", "relative (division)", None))
        self.corrMode.setItemText(4, _translate("SLGADialog", "relative with forgetting (division)", None))
        self.corrMode.setItemText(5, _translate("SLGADialog", "logistic", None))
        self.corrMode.setItemText(6, _translate("SLGADialog", "diversity", None))
        self.corrMode.setItemText(7, _translate("SLGADialog", "disturbance", None))
        self.corrMode.setItemText(8, _translate("SLGADialog", "survivor", None))
        self.corrMode.setItemText(9, _translate("SLGADialog", "improved percent", None))
        self.corrMode.setItemText(10, _translate("SLGADialog", "deviation", None))
        self.corrMode.setItemText(11, _translate("SLGADialog", "iterations without improvement", None))
        self.label_12.setText(_translate("SLGADialog", "Correction parameter #1:", None))
        self.label_13.setText(_translate("SLGADialog", "Correction parameter #2:", None))
        self.use_metamodels.setText(_translate("SLGADialog", "Use metamodels", None))
        self.label_5.setText(_translate("SLGADialog", "Metamodel:", None))
        self.comboBox.setItemText(0, _translate("SLGADialog", "Averaging", None))
        self.comboBox.setItemText(1, _translate("SLGADialog", "KNearestNeighbours", None))
        self.comboBox.setItemText(2, _translate("SLGADialog", "Neural Network", None))
        self.comboBox.setItemText(3, _translate("SLGADialog", "Support Vector Regression", None))
        self.comboBox.setItemText(4, _translate("SLGADialog", "Linear Regression", None))
        self.comboBox.setItemText(5, _translate("SLGADialog", "Random", None))
        self.label_4.setText(_translate("SLGADialog", "Population control percent:", None))
        self.pushButton.setText(_translate("SLGADialog", "Run", None))

import resources_rc
